- name: Remove nginx
  hosts: white
  become: True
  tasks:
    - name: Stop service nginx, if started
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Uninstall nginx
      apt:
        name: nginx
        state: absent    

    - name: Delete nginx folder
      file:
        path: /etc/nginx
        state: absent    
